name: Test for example-app-1

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/example-app-1/**.php'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy .env
        run: |
          cp src/example-app-1/.env.example src/example-app-1/.env

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: src/example-app-1/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('src/example-app-1/composer.lock') }}

      - name: Install Dependencies
        run: |
          cd src/example-app-1
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: cd src/example-app-1 && php artisan key:generate

      - name: Directory Permissions
        run: cd src/example-app-1 && chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: cd src/example-app-1 && vendor/bin/phpunit
